inference_node:
    ros__parameters:
        model_name: "policy_amp.onnx"
        act_alpha: 1.0
        gyro_alpha: 1.0
        angle_alpha: 1.0
        obs_num: 78
        frame_stack: 1
        joint_num: 23
        decimation: 4
        intra_threads: 1
        dt: 0.005
        obs_scales_lin_vel: 1.0
        obs_scales_ang_vel: 1.0
        obs_scales_dof_pos: 1.0
        obs_scales_dof_vel: 1.0
        obs_scales_gravity_b: 1.0
        clip_observations: 100.0
        action_scale: 0.25
        clip_actions: 100.0