inference_node:
    ros__parameters:
        motor_id: 
            [1, 2, 3, 4, 5, 6,
             7, 8, 9, 10, 11, 12, 13,
             14, 15, 16, 17, 18,
             19, 20, 21, 22, 23]
        motor_interface_type: "can"
        motor_interface: ["can0", "can1", "can2", "can3"]
        motor_num: [6, 7, 5, 5]
        motor_type: "DM"
        motor_model: 
            [1, 1, 1, 1, 0, 0,
             1, 1, 1, 1, 0, 0, 1,
             0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0]
        master_id_offset: 16
