imu:
    imu_id: 8
    imu_interface_type: "serial"
    imu_interface: "/dev/ttyACM0"
    imu_type: "HIPNUC"
    baudrate: 921600

motors:
    motor_id: 
    [0x31, 0x32, 0x33, 0x34, 0x35, 0x36,
     0x41, 0x42, 0x43, 0x44, 0x45, 0x46,
     0x11, 0x12, 0x13, 0x14, 0x51,
     0x21, 0x22, 0x23, 0x24, 0x52, 0x53]
    motor_interface_type: "can"
    motor_interface: ["can0", "can1", "can2", "can3"]
    motor_num: [6, 6, 5, 6]
    motor_type: "DM"
    motor_model: 
        [0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0,]
    master_id_offset: 10

robot:
    kp: 
        [10.0, 10.0, 10.0, 10.0, 10.0, 10.0,
         10.0, 10.0, 10.0, 10.0, 10.0, 10.0,
         10.0, 10.0, 10.0, 10.0, 10.0,
         10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    kd: 
        [1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
         1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
         1.0, 1.0, 1.0, 1.0, 1.0,
         1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    motor_sign: 
        [ 1,  1,  1,  1,  1,  1,
          1,  1, -1, -1, -1,  1,
          1,  1,  1,  1,  1,
         -1,  1,  1, -1,  1, 1]
    close_chain_motor_id:
        [5, 6,
         11, 12]
