inference_node:
    ros__parameters:
        clip_cmd: 
            [-0.5, 2.5,
             -0.5, 0.5,
             -1.57, 1.57]
        usd2urdf: [0, 6, 12, 1, 7, 13, 18, 2, 8, 14, 19, 3, 9, 15, 20, 4, 10, 16, 21, 5, 11, 17, 22]
        kp: 
            [100.0, 100.0, 100.0, 150.0, 40.0, 40.0,
             100.0, 100.0, 100.0, 150.0, 40.0, 40.0, 150.0,
             40.0, 40.0, 40.0, 30.0, 20.0,
             40.0, 40.0, 40.0, 30.0, 20.0]
        kd: 
            [3.3, 3.3, 3.3, 5.0, 2.0, 2.0,
             3.3, 3.3, 3.3, 5.0, 2.0, 2.0, 5.0,
             2.0, 2.0, 2.0, 1.5, 1.0,
             2.0, 2.0, 2.0, 1.5, 1.0]
        motor_sign: 
            [1, 1, 1, 1, 1, 1,
             1, 1, -1, -1, -1, -1, 1,
             1, 1, 1, 1, 1,
             -1, 1, 1, -1, 1]
        close_chain_motor_id:
            [5, 6,
             11, 12]
        joint_default_angle: 
            [0.0, 0.0, -0.1, 0.3, -0.2, 0.0,
             0.0, 0.0, -0.1, 0.3, -0.2, 0.0, 0.0,
             0.18, 0.06, 0.0, 0.78, 0.0,
             0.18, -0.06, 0.0, 0.78, 0.0]
        joint_limits: 
            [-1.0, 0.6,
             -0.6, 1.0,
             -1.57, 1.57,
             -0.2, 2.5,
             -0.6, 0.6,
             -0.5, 0.5,
             -0.6, 1.0,
             -1.0, 0.6,
             -1.57, 1.57,
             -0.2, 2.5,
             -0.6, 0.6,
             -0.5, 0.5,
             -3.14, 3.14,
             -3.14, 1.57,
             -0.25, 3.14,
             -1.57, 1.57,
             -0.6, 1.57,
             -1.57, 1.57,
             -3.14, 1.57,
             -3.14, 0.25,
             -1.57, 1.57,
             -0.6, 1.57,
             -1.57, 1.57]
        gravity_z_upper: -0.7